openapi: 3.1.0
info:
  version: 1.0.0
  title: 'Ultorex API documentation'
  termsOfService: 'https://ultorex.io/'
  contact:
    email: 'support@ultorex.io'
    url: 'https://ultorex.io'
  x-logo:
    url: 'https://ultorex-public-setting-files.s3.ap-southeast-1.amazonaws.com/logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Trade
    description: Trading
servers:
  - url: 'https://api.ultorex.io/api'
paths:
  /coinmarketcap/summary:
    $ref: paths/trade/summary.yaml
  /coinmarketcap/assets:
    $ref: paths/trade/assets.yaml
  /coinmarketcap/ticker:
    $ref: paths/trade/ticker.yaml
  /coinmarketcap/orderbook/{market_pair}:
    $ref: paths/trade/orderbook.yaml
  /coinmarketcap/trades/{market_pair}:
    $ref: paths/trade/trades.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
